version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432" 
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/db-files/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data
